services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Divante\ScheduledExportBundle\Controller\:
          resource: '../../Controller'
          public: true
          tags: ['controller.service_arguments']

    Divante\ScheduledExportBundle\Command\:
      resource: '../../Command/*'
      tags: ['console.command']

    Divante\ScheduledExportBundle\Installer:
      public: true
      arguments:
        $bundle: "@=service('kernel').getBundle('DivanteScheduledExportBundle')"

    scheduledExport:
        class : Elements\Bundle\ProcessManagerBundle\Executor\Callback\General
        arguments :
            $name: "scheduledExport"
            $extJsClass: "pimcore.plugin.processmanager.executor.callback.scheduledExport"
            $jsFile: "/bundles/divantescheduledexport/js/process-manager/scheduled-export.js"
        tags:
            - { name: "elements.processManager.executorCallbackClasses" }
