name: Analysis
on: [push]

jobs:
  build:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: phpcs
      run: |
        composer global require "divante-ltd/pimcore-coding-standards":"^0.1" \
          --no-interaction --prefer-dist --ignore-platform-reqs --quiet
        /home/runner/.composer/vendor/bin/phpcs --config-set colors 1
        /home/runner/.composer/vendor/bin/phpcs \
          --extensions=php \
          --standard=/home/runner/.composer/vendor/divante-ltd/pimcore-coding-standards/Standards/Pimcore5/ruleset.xml \
          ./src  -s
