name: Tests
on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pimcore_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Setup DB
        run: |
          mysql --version
          mysql -e "SET GLOBAL innodb_file_format=Barracuda;"
          mysql -e "SET GLOBAL innodb_large_prefix=1;"

      - name: Checkout Repository
        uses: actions/checkout@v1
